### put request to update a snippet
PUT http://localhost:4001/api/snippets/28e701c4-406e-4e91-a235-304100bb5bde
Content-Type: application/json

{
  "title": "new Code",
  "description": "Useful array manipulation functions in java",
  "language": "Java",
  "sourceCode": "const unique = arr => [...new Set(arr)];",
  "tags": ["java"],
  "favorite": true
}
###