### POST request to create a new snippet
POST http://localhost:4001/api/snippets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Array Utilities",
  "description": "Useful array manipulation functions",
  "language": "JavaScript",
  "sourceCode": "const unique = arr => [...new Set(arr)];",
  "tags": ["javascript", "utilities", "arrays"],
  "favorite": false
}

###
POST http://localhost:4001/api/snippets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "new user 2",
  "description": "new user 2",
  "language": "Java",
  "sourceCode": "new user 2",
  "tags": ["javas", "utilities", "arrays"],
  "favorite": true
}
###