version: '3.8'

services:
  snippet-db:
    image: postgres:latest
    container_name: snippet-db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      TZ: Asia/Kolkata
    ports:
      - "5001:5432"
    volumes:
      - snippet_db_data:/var/lib/postgresql/data
    networks:
      - internal


  snippet-service:
    build: .
    container_name: snippet-service
    restart: always
    environment:
      SERVER_PORT: 4001
      SPRING_DATASOURCE_URL: jdbc:postgresql://snippet-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4001:4001"
    networks:
      - internal
    depends_on:
      - snippet-db

networks:
  internal:
    driver: bridge

volumes:
  snippet_db_data: