spring.application.name=snippet_shelf_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/SnippetShelf_v1
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always